# Generated by Django 2.2.7 on 2019-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('student_phone', models.CharField(max_length=14)),
                ('guardians_phone', models.CharField(max_length=14)),
                ('college', models.CharField(max_length=64)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year')], max_length=1)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
